In [ ]:
import pandas as pd
data = {
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}
df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [ ]:
#.sum()
df.groupby(['Department','Experience']).sum()

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [ ]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64

In [ ]:
df2 = df.groupby('Department').sum()
print(df2)

           Employee  Salary  Experience
Department
HR               AF  122000           9
IT               CE  115000           9
Sales           BDG  179000          14

In [ ]:
#Custom aggregations
df.groupby('Department').agg({'Salary':'sum','Experience':'mean'})

            Salary  Experience
Department
HR          122000    4.500000
IT          115000    4.500000
Sales       179000    4.666667

In [ ]:
#Broadcast group mean to each row
df9 = df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
print(df9)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Salary, dtype: float64

In [ ]:
#Filtering groups
df1 = df.groupby('Department').filter(lambda x : len(x)>2)
print(df1)

  Department Employee  Salary  Experience  Dept_Avg_Salary
1      Sales        B   60000           4     59666.666667
3      Sales        D   48000           5     59666.666667
6      Sales        G   71000           5     59666.666667

In [ ]:
#Pivot tables
#Mean salary by department and experience
df.pivot_table(
    values = 'Salary',
    index = 'Department',
    columns = 'Experience',
    aggfunc = 'mean'
)

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [ ]:
import pandas as pd
data = {
    'Crop':['Rice','Wheat','Maize','Rice','Wheat','Maize','Rice'],
    'Farmer':['Surya','Raju','Dinesh','Lakshmi','Monika','Bhargav','Dileep'],
    'Season':['Kharif','Rabi','Kharif','Kharif','Rabi','Kharif','Rabi'],
    'Yield':[50,45,40,55,48,42,60],
    'Area':[2,1.5,2,2.5,1.8,2,3]
    }
df = pd.DataFrame(data)
print(df)

    Crop   Farmer  Season  Yield  Area
0   Rice    Surya  Kharif     50   2.0
1  Wheat     Raju    Rabi     45   1.5
2  Maize   Dinesh  Kharif     40   2.0
3   Rice  Lakshmi  Kharif     55   2.5
4  Wheat   Monika    Rabi     48   1.8
5  Maize  Bhargav  Kharif     42   2.0
6   Rice   Dileep    Rabi     60   3.0

In [ ]:
df1 = df.groupby(['Crop','Yield']).sum()
print(df1)

              Farmer  Season  Area
Crop  Yield
Maize 40      Dinesh  Kharif   2.0
      42     Bhargav  Kharif   2.0
Rice  50       Surya  Kharif   2.0
      55     Lakshmi  Kharif   2.5
      60      Dileep    Rabi   3.0
Wheat 45        Raju    Rabi   1.5
      48      Monika    Rabi   1.8

In [ ]:
df2 = df.groupby('Crop').sum()
print(df2)

                   Farmer            Season  Yield  Area
Crop
Maize       DineshBhargav      KharifKharif     82   4.0
Rice   SuryaLakshmiDileep  KharifKharifRabi    165   7.5
Wheat          RajuMonika          RabiRabi     93   3.3

In [ ]:
df.groupby('Crop').agg({
    'Yield':'sum',
    'Area':'mean'
    })

       Yield  Area
Crop
Maize     82  2.00
Rice     165  2.50
Wheat     93  1.65

In [ ]:
df.groupby(['Crop','Farmer']).agg({
    'Yield':'sum',
    'Area':'mean'
    })

               Yield  Area
Crop  Farmer
Maize Bhargav     42   2.0
      Dinesh      40   2.0
Rice  Dileep      60   3.0
      Lakshmi     55   2.5
      Surya       50   2.0
Wheat Monika      48   1.8
      Raju        45   1.5

In [ ]:
df4 = df["Crop_Avg_Yield"] = df.groupby('Crop')['Yield'].transform('mean')
print(df4)

0    55.0
1    46.5
2    41.0
3    55.0
4    46.5
5    41.0
6    55.0
Name: Yield, dtype: float64

In [ ]:
df1 = df.groupby('Crop').filter(lambda x : len(x)>2)
print(df1)

   Crop   Farmer  Season  Yield  Area  Crop_Avg_Yield
0  Rice    Surya  Kharif     50   2.0            55.0
3  Rice  Lakshmi  Kharif     55   2.5            55.0
6  Rice   Dileep    Rabi     60   3.0            55.0

In [ ]:
df.pivot_table(
    values = 'Yield',
    index = 'Crop',
    columns = 'Farmer',
    aggfunc = 'sum'
)

Farmer  Bhargav  Dileep  Dinesh  Lakshmi  Monika  Raju  Surya
Crop
Maize      42.0     NaN    40.0      NaN     NaN   NaN    NaN
Rice        NaN    60.0     NaN     55.0     NaN   NaN   50.0
Wheat       NaN     NaN     NaN      NaN    48.0  45.0    NaN

In [ ]:
import pandas as pd
data = {
    'Name':['Ravi','Asha','Siddhu','Ravi','Asha'],
    'Subject':['Math','Science','Math','Science','Social'],
    'Marks':[85,90,78,82,95]
}
df = pd.DataFrame(data)
print(df)

     Name  Subject  Marks
0    Ravi     Math     85
1    Asha  Science     90
2  Siddhu     Math     78
3    Ravi  Science     82
4    Asha   Social     95

In [ ]:
df.groupby(['Subject','Marks']).sum()

                 Name
Subject Marks
Math    78     Siddhu
        85       Ravi
Science 82       Ravi
        90       Asha
Social  95       Asha

In [ ]:
df.pivot_table(
    values = 'Marks',
    index = 'Name',
    columns = 'Subject',
    aggfunc = 'sum'
)

Subject  Math  Science  Social
Name
Asha      NaN     90.0    95.0
Ravi     85.0     82.0     NaN
Siddhu   78.0      NaN     NaN

In [ ]:
df2 = df.groupby('Name').sum()
print(df2)

              Subject  Marks
Name
Asha    ScienceSocial    185
Ravi      MathScience    167
Siddhu           Math     78